### ISSUE TITLE
Problem in base_training

### ISSUE THREAD

**Issue by zynhhh** [csuhan/VFA#8]
Thanks you for your work, but when I was running` python train.py configs/vfa/voc/vfa_split1/vfa_r101_c4_8xb4_voc-split1_base-training.py`, the code reported an error. Could you help me see where the problem is？
Here is the error：

> 2023-04-23 20:57:54,654 - mmfewshot - INFO - Exp name: vfa_r101_c4_8xb4_voc-split1_base-training.py
> 2023-04-23 20:57:54,654 - mmfewshot - INFO - Iter [3000/18000]  lr: 2.000e-02, eta: 1:13:18, time: 0.344, data_time: 0.015, memory: 12341, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, loss_bbox: nan, acc: 5.6250, loss_meta_cls: nan, meta_acc: 6.6667, loss_vae: nan, loss: nan
> 2023-04-23 20:57:54,656 - mmdet - INFO - starting model initialization...
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3000/3000, 300.0 task/s, elapsed: 10s, ETA:     0s2023-04-23 20:58:04,709 - mmdet - INFO - model initialization done.
> [                                                  ] 0/4952, elapsed: 0s, ETA:Traceback (most recent call last):
>   File "train.py", line 252, in <module>
>     main()
>   File "train.py", line 241, in main
>     train_detector(
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/apis/train.py", line 197, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
>     iter_runner(iter_loaders[i], **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
>     self.call_hook('after_train_iter')
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 232, in after_train_iter
>     self._do_evaluate(runner)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/core/evaluation/eval_hooks.py", line 47, in _do_evaluate
>     results = single_gpu_test(runner.model, self.dataloader, show=False)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/apis/test.py", line 45, in single_gpu_test
>     result = model(mode='test', rescale=True, **data)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
>     return super().forward(*inputs, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/models/detectors/query_support_detector.py", line 173, in forward
>     return self.forward_test(img, img_metas, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
>     return self.simple_test(imgs[0], img_metas[0], **kwargs)
>   File "/media/hdd0/xiaopeng/zyn/VFA-source/VFA-1.0.0/vfa/vfa_detector.py", line 100, in simple_test
>     bbox_results = super().simple_test(img, img_metas, proposals, rescale)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/models/detectors/meta_rcnn.py", line 176, in simple_test
>     return self.roi_head.simple_test(
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmfewshot/detection/models/roi_heads/meta_rcnn_roi_head.py", line 272, in simple_test
>     det_bboxes, det_labels = self.simple_test_bboxes(
>   File "/media/hdd0/xiaopeng/zyn/VFA-source/VFA-1.0.0/vfa/vfa_roi_head.py", line 281, in simple_test_bboxes
>     det_bbox, det_label = self.bbox_head.get_bboxes(
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 369, in get_bboxes
>     det_bboxes, det_labels = multiclass_nms(bboxes, scores,
>   File "/home/xiaopeng/anaconda3/envs/zyn-vfa/lib/python3.8/site-packages/mmdet/core/post_processing/bbox_nms.py", line 38, in multiclass_nms
>     bboxes = multi_bboxes.view(multi_scores.size(0), -1, 4)
> RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 4] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by csuhan** [comment]
Our config is for 8 GPU training. You need to change the learning rate. For example, lr = 0.02 / 8 for single gpu training.

**Comment by zynhhh** [comment]
Thank you，it works. 

> Our config is for 8 GPU training. You need to change the learning rate. For example, lr = 0.02 / 8 for single gpu training.

**Comment by dogdog258** [comment]
Thanks you for your work, but when I was running python train.py configs/vfa/voc/vfa_split1/vfa_r101_c4_8xb4_voc-split1_base-training.py with lr=0.02/8=0.0025, I just got reslult AP50: 0.7520, mAP: 0.7525, It still falls short of the 78.6 accuracy stated in the original article. Could you  tell me how to solve this problem.  My device is single GPU RTX4090
